
const STAGES=["Contacted","Pending for Follow-up","Follow-up Done","Waiting for Response","Photo Received","Junk"];
const STAGE_COLORS={"Contacted":"#3b82f6","Pending for Follow-up":"#f59e0b","Follow-up Done":"#8b5cf6","Waiting for Response":"#10b981","Photo Received":"#0f9aa8","Junk":"#dc3545"};
const BITRIX_LANGUAGE_NAMES={"45":"English","221":"Italiano","215":"Français","217":"Español","209":"Română","223":"Deutsch","49":"Русский","213":"Türkçe","211":"Polski","47":"Português","7103":"Ελληνικά","7119":"Bosnian","10309":"Bulgarian"};
let templates=[], leads=[], contacts=[], conversations=[], statuses=[], countries=[], selectedConversation=null, selectedStage="Contacted", selectedLeadIds=new Set(), bitrixLeads=[], newestBitrixId=null, templateConfigs={};
let leadSearchTimer=null;

async function api(url,options={}){const agentId=localStorage.getItem("rh_agent_id")||"";const r=await fetch(url,{headers:{"Content-Type":"application/json",...(agentId?{"X-Agent-Id":agentId}:{}),...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function fmt(v){if(!v)return"—";try{return new Date(v).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})}catch{return v}}
function fmtDate(v){if(!v)return"—";try{return new Date(v).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}catch{return v}}
function langName(v){return BITRIX_LANGUAGE_NAMES[String(v)]||String(v||"Not set")}
function initials(name){return String(name||"?").split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function toast(msg,error=false){const e=document.getElementById("toast");e.textContent=msg;e.classList.toggle("error",error);e.classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove("show"),3200)}
function showSection(name){document.querySelectorAll(".menu-item").forEach(x=>x.classList.toggle("active",x.dataset.section===name));document.querySelectorAll(".section").forEach(x=>x.classList.toggle("active",x.id==="section-"+name));if(name==="dashboard")loadDashboard();if(name==="lead-manager")loadLeadManager();if(name==="bitrix")loadBitrixLeads();if(name==="broadcast")loadCampaigns();if(name==="inbox")loadInbox();if(name==="webhooks")loadStatuses();if(name==="contacts"){loadContacts();loadLabels()}if(name==="templates")loadTemplates();if(name==="activity")loadActivity();if(name==="settings")loadSettings();if(name==="analytics")loadAnalytics();if(name==="ai-assistant")loadAiAssistant();if(name==="team")loadTeam()}
document.querySelectorAll(".menu-item").forEach(x=>x.addEventListener("click",()=>showSection(x.dataset.section)));
function closeModal(){document.getElementById("modalBackdrop").classList.remove("show");document.getElementById("modalBody").innerHTML=""}
function backdropClose(e){if(e.target.id==="modalBackdrop")closeModal()}
function openModal(title,body){document.getElementById("modalTitle").textContent=title;document.getElementById("modalBody").innerHTML=body;document.getElementById("modalBackdrop").classList.add("show")}
function toggleNumberMenu(){document.getElementById("numberPicker").classList.toggle("open")}
document.addEventListener("click",e=>{if(!e.target.closest("#numberPicker"))document.getElementById("numberPicker").classList.remove("open")})

async function loadDashboard(){try{const d=await api("/api/dashboard/stats");const s=d.leadStats||{};const cards=[["Contacted",s["Contacted"]||0,"Initial outreach","📨"],["Pending",s["Pending for Follow-up"]||0,"Follow-up due","⏳"],["Waiting",s["Waiting for Response"]||0,"Awaiting customer","💬"],["Photos",s["Photo Received"]||0,"Cases ready for review","📸"],["Junk",s["Junk"]||0,"Suppressed leads","🚫"],["Messages",d.totalMessages||0,"WhatsApp activity","✉️"]];document.getElementById("dashboardStats").innerHTML=cards.map(x=>`<div class="card stat kpi-v2"><div class="kpi-top"><div class="kpi-label">${x[0]}</div><div class="kpi-icon">${x[3]}</div></div><div class="kpi-value">${x[1]}</div><div class="kpi-note">${x[2]}</div></div>`).join("");const contacted=d.contacted||0;const colors=["#3b82f6","#f59e0b","#8b5cf6","#10b981","#0f9aa8","#dc4f61"];document.getElementById("dashboardFunnel").innerHTML=STAGES.map((stage,i)=>{const n=s[stage]||0,p=contacted?Math.round(n/contacted*100):0;return `<div class="funnel-row"><span>${esc(stage)}</span><div class="funnel-bar"><i style="width:${Math.min(100,p)}%;background:${colors[i]}"></i></div><b>${n}</b></div>`}).join("");let attention=[];try{const ld=await api("/api/leads?limit=500");const arr=ld.data||[];attention=arr.filter(l=>l.stage!=="Junk").sort((a,b)=>new Date(a.followup1DueAt||a.followup2DueAt||"2999-01-01")-new Date(b.followup1DueAt||b.followup2DueAt||"2999-01-01")).slice(0,6)}catch{}document.getElementById("dashboardAttention").innerHTML=attention.length?attention.map(l=>{const urgent=l.stage==="Photo Received"?"📸":(dueText(l)==="Due now"?"⚡":"⏱️");return `<div class="attention-item"><div class="attention-icon">${urgent}</div><div class="attention-main"><b>${esc(l.name||l.phone)}</b><span>${esc(l.phone)} · ${esc(l.stage||"New")} · ${esc(dueText(l)||"No due date")}</span></div><span class="attention-action" onclick="openLead('${esc(l.id)}')">Open →</span></div>`}).join(""):`<div class="empty">Nothing urgent right now. Nice work. ✨</div>`;document.getElementById("donut")?.remove();}catch(e){toast(e.message,true)}}
function makeDonut(s,total){if(!total)return"conic-gradient(#dfecef 0 100%)";let pos=0;const colors=["#3b82f6","#f59e0b","#8b5cf6","#d97706","#10b981","#0f9aa8","#dc3545"];const parts=[];STAGES.forEach((st,i)=>{const p=(s[st]||0)/total*100;parts.push(`${colors[i]} ${pos}% ${pos+p}%`);pos+=p});return`conic-gradient(${parts.join(",")})`}

function stagePill(stage){const c=STAGE_COLORS[stage]||"#64748b";return`<span class="stage-pill" style="color:${c};background:${c}16;border:1px solid ${c}33"><span class="stage-dot" style="background:${c}"></span>${esc(stage)}</span>`}
function dueText(lead){const due=lead.followup2DueAt||lead.followup1DueAt;if(!due)return"";const ms=new Date(due)-Date.now();if(ms<=0)return"Due now";const d=Math.ceil(ms/86400000);return d===1?"Tomorrow":`in ${d} days`}
function populateStageControls(){document.getElementById("bulkStage").innerHTML=`<option value="">Move selected to…</option>`+STAGES.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join("");document.getElementById("inboxStageFilter").innerHTML=`<option value="">All stages</option>`+STAGES.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join("")}
async function loadLeadManager(){try{const q=new URLSearchParams();const s=document.getElementById("leadSearch")?.value.trim();const l=document.getElementById("leadLanguage")?.value;if(s)q.set("q",s);if(l)q.set("language",l);const f=document.getElementById("leadFrom")?.value,t=document.getElementById("leadTo")?.value;if(f)q.set("from",f);if(t)q.set("to",t);const d=await api("/api/leads?"+q.toString());leads=d.data||[];window.__leadCache=leads;renderStageTabs();renderLeadCards()}catch(e){toast(e.message,true)}}
function debouncedLoadLeads(){clearTimeout(leadSearchTimer);leadSearchTimer=setTimeout(loadLeadManager,280)}
function renderStageTabs(){const counts={};STAGES.forEach(s=>counts[s]=leads.filter(l=>l.stage===s).length);document.getElementById("stageTabs").innerHTML=STAGES.map(s=>`<button class="stage-tab ${selectedStage===s?"active":""}" onclick="selectedStage='${esc(s)}';selectedLeadIds.clear();renderStageTabs();renderLeadCards()"><span class="stage-dot" style="background:${STAGE_COLORS[s]}"></span><span class="stage-name">${esc(s)}</span><span class="stage-count">${counts[s]||0}</span></button>`).join("");const importBtn=document.getElementById("importContactedBtn");if(importBtn)importBtn.style.display=selectedStage===STAGES[0]?"inline-flex":"none"}
function renderLeadCards(){const grid=document.getElementById("leadGrid");const filtered=leads.filter(l=>l.stage===selectedStage);if(!filtered.length){grid.innerHTML=`<div class="card empty" style="grid-column:1/-1">No leads in <b>${esc(selectedStage)}</b> for the selected filters.</div>`;document.getElementById("selectedCount").textContent="0 selected";document.getElementById("selectAllLeads").checked=false;return}grid.innerHTML=filtered.map(l=>`<div class="lead-card"><input class="check lead-check" type="checkbox" ${selectedLeadIds.has(l.id)?"checked":""} onchange="toggleLead('${esc(l.id)}',this.checked)"><div class="lead-top" onclick="openLead('${esc(l.id)}')"><div class="avatar">${esc(initials(l.name))}</div><div style="min-width:0"><div class="lead-name">${esc(l.name)}</div><div class="lead-phone">${esc(l.phone)} · ${esc(l.language||"Language not set")}</div></div></div>${stagePill(l.stage)}<div class="lead-meta"><div class="meta-box"><b>Contacted</b><span>${fmtDate(l.contactedAt)}</span></div><div class="meta-box"><b>Next action</b><span class="small-counter">${esc(dueText(l)||"—")}</span></div></div><div class="lead-actions"><button class="btn btn-light btn-sm" onclick="openLead('${esc(l.id)}')">View</button><button class="btn btn-primary btn-sm" onclick="openLeadSender('${esc(l.id)}')">WhatsApp</button></div></div>`).join("");document.getElementById("selectedCount").textContent=`${selectedLeadIds.size} selected`;document.getElementById("selectAllLeads").checked=filtered.length>0&&filtered.every(l=>selectedLeadIds.has(l.id))}

let contactImportSelection=new Set();
function openContactImportToContacted(){
  contactImportSelection=new Set();
  const labels=[...new Set(contacts.flatMap(c=>c.labels||[]))].sort();
  openModal("Import Contacts → Contacted",`<div class="hint" style="margin-bottom:12px">Select contacts that have already been reached out to. They will be created/updated as Lead Manager cards and placed in <b>Contacted</b>.</div><div class="toolbar"><input class="search" id="contactImportSearch" placeholder="Search name or phone…" oninput="renderContactImportPicker()"><select id="contactImportLabel" onchange="renderContactImportPicker()"><option value="">All labels</option>${labels.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("")}</select></div><div class="select-tools" style="margin-top:10px"><label style="display:flex;align-items:center;gap:7px;font-size:11px"><input type="checkbox" id="contactImportSelectAll" onchange="toggleContactImportAll(this.checked)"> Select all visible</label><span class="selected-count" id="contactImportCount">0 selected</span></div><div id="contactImportList" style="max-height:420px;overflow:auto;border:1px solid rgba(20,70,100,.08);border-radius:12px"></div><div class="actions" style="margin-top:14px"><button class="btn btn-light" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="importSelectedContactsToContacted()">Add to Contacted</button></div>`);renderContactImportPicker();}
function contactImportVisible(){const q=(document.getElementById("contactImportSearch")?.value||"").toLowerCase().trim(),label=document.getElementById("contactImportLabel")?.value||"";return contacts.filter(c=>(!q||[c.name,c.phone,c.language].some(v=>String(v||"").toLowerCase().includes(q)))&&(!label||(c.labels||[]).includes(label)));}
function renderContactImportPicker(){const arr=contactImportVisible(),box=document.getElementById("contactImportList");if(!box)return;box.innerHTML=arr.length?arr.map(c=>`<label style="display:flex;align-items:center;gap:10px;padding:10px 12px;border-bottom:1px solid rgba(20,70,100,.06);cursor:pointer"><input type="checkbox" ${contactImportSelection.has(c.id)?"checked":""} onchange="toggleContactImport('${esc(c.id)}',this.checked)"><div style="min-width:0;flex:1"><b style="font-size:11px">${esc(c.name||c.phone)}</b><div class="hint">${esc(c.phone)} · ${esc(c.language||"Language not set")}</div></div><span class="hint">${esc((c.labels||[]).join(", ")||"")}</span></label>`).join(""):`<div class="empty">No contacts found.</div>`;document.getElementById("contactImportCount").textContent=`${contactImportSelection.size} selected`;document.getElementById("contactImportSelectAll").checked=arr.length>0&&arr.every(c=>contactImportSelection.has(c.id));}
function toggleContactImport(id,checked){checked?contactImportSelection.add(id):contactImportSelection.delete(id);renderContactImportPicker()}
function toggleContactImportAll(checked){contactImportVisible().forEach(c=>checked?contactImportSelection.add(c.id):contactImportSelection.delete(c.id));renderContactImportPicker()}
async function importSelectedContactsToContacted(){const ids=[...contactImportSelection];if(!ids.length)return toast("Select at least one contact",true);try{const r=await api("/api/leads/import-contacts",{method:"POST",body:JSON.stringify({contactIds:ids})});closeModal();toast(`${r.added+r.updated-r.skipped} contacts added to Contacted`);selectedStage=STAGES[0];await loadLeadManager()}catch(e){toast(e.message,true)}}
function toggleLead(id,checked){checked?selectedLeadIds.add(id):selectedLeadIds.delete(id);renderLeadCards()}
function toggleSelectAllLeads(checked){leads.filter(l=>l.stage===selectedStage).forEach(l=>checked?selectedLeadIds.add(l.id):selectedLeadIds.delete(l.id));renderLeadCards()}
async function bulkMoveStage(){const stage=document.getElementById("bulkStage").value;if(!stage||!selectedLeadIds.size)return toast("Select a stage and at least one lead");try{await api("/api/leads/bulk-stage",{method:"POST",body:JSON.stringify({leadIds:[...selectedLeadIds],stage})});toast(`${selectedLeadIds.size} leads moved`);selectedLeadIds.clear();await loadLeadManager()}catch(e){toast(e.message,true)}}
async function openLead(id){try{const d=await api(`/api/leads/${encodeURIComponent(id)}`);const l=d.data;openModal(l.name||"Lead",leadModalHtml(l))}catch(e){toast(e.message,true)}}
function leadModalHtml(l){
  const timeline=(l.stageHistory||[]).slice().reverse().map(x=>`<div class="lead-timeline-item"><b>${stagePill(x.stage)}</b><span>${fmt(x.at)} · ${esc(x.reason||"Stage updated")}</span></div>`).join("")||`<div class="hint">No stage history yet.</div>`;
  const photoStage=l.stage==="Photo Received";
  const score=leadScore(l);
  const due=l.followup2DueAt||l.followup1DueAt;
  return `<div>
    <div class="lead-360-head"><div class="lead-360-avatar">${esc(initials(l.name))}</div><div style="min-width:0;flex:1"><div class="lead-360-title">${esc(l.name||"Unnamed lead")}</div><div class="lead-360-sub">${esc(l.phone)} · ${esc(l.language||"Language not set")} · Bitrix ${esc(l.bitrixId||"—")}</div><div style="margin-top:7px">${stagePill(l.stage||"New")}</div></div></div>
    <div class="lead-360-actions"><button class="btn btn-primary btn-sm" onclick="openLeadSender('${esc(l.id)}')">💬 WhatsApp</button><button class="btn btn-light btn-sm" onclick="openConversation('${esc(l.phone)}');closeModal();showSection('inbox')">Open Inbox</button><button class="btn btn-light btn-sm" onclick="closeModal()">Close</button></div>
    <div class="lead-info-grid">
      <div class="lead-info-box"><b>First contacted</b><span>${fmt(l.contactedAt)}</span></div><div class="lead-info-box"><b>Next action</b><span>${esc(dueText(l)||"No pending action")}</span></div>
      <div class="lead-info-box"><b>Follow-up 1</b><span>${fmt(l.followup1SentAt)}</span></div><div class="lead-info-box"><b>Follow-up 2</b><span>${fmt(l.followup2SentAt)}</span></div>
      <div class="lead-info-box"><b>Last message</b><span>${fmt(l.lastMessageAt)}</span></div><div class="lead-info-box"><b>Source</b><span>${esc(l.source||"Bitrix")}</span></div>
    </div>
    <div class="lead-360-section"><h4>Lead quality</h4><div class="lead-score"><b style="font-size:12px">${score}/100</b><div class="lead-score-track"><i style="width:${score}%"></i></div><span class="hint">${score>=70?"Hot":score>=40?"Warm":"New"}</span></div></div>
    <div class="lead-360-section"><h4>Photo qualification</h4><div class="photo-state"><span style="font-size:18px">${photoStage?"📸":"🖼️"}</span><div><strong>${photoStage?"Photos received":"Photos not received yet"}</strong><span>${photoStage?"Medical team can review the submitted case.":"Ask the lead to send clear front, sides and back photos."}</span></div></div></div>
    <div class="lead-360-section"><h4>Assignment</h4><div class="field"><label>Assigned agent</label><select id="modalAgent"><option value="">Unassigned</option>${(teamData?.agents||[]).map(a=>`<option value="${esc(a.id)}" ${l.assignedAgentId===a.id?"selected":""}>${esc(a.name)} · ${esc(a.role)}</option>`).join("")}</select></div><button class="btn btn-light btn-sm" onclick="assignLeadFromModal('${esc(l.id)}')">Save assignment</button></div>
    <div class="lead-360-section"><h4>Stage & follow-up</h4><div class="field"><label>Move to stage</label><select id="modalStage">${STAGES.map(s=>`<option ${l.stage===s?"selected":""}>${esc(s)}</option>`).join("")}</select></div><div class="actions"><button class="btn btn-light btn-sm" onclick="moveLeadFromModal('${esc(l.id)}')">Save stage</button><button class="btn btn-danger btn-sm" onclick="deleteLead('${esc(l.id)}')">Delete lead</button></div></div>
    <div class="lead-360-section"><h4>Timeline</h4><div class="lead-timeline">${timeline}</div></div>
  </div>`;
}
function leadScore(l){let score=20;if(l.contactedAt)score+=20;if(l.stage==="Pending for Follow-up")score+=15;if(l.stage==="Waiting for Response")score+=20;if(l.stage==="Photo Received")score+=35;if(l.lastMessageAt)score+=5;if(l.optOut||l.stage==="Junk")score=0;return Math.min(100,score)}

async function assignLeadFromModal(id){const agentId=document.getElementById("modalAgent")?.value||"";try{await api(`/api/leads/${id}/assign`,{method:"POST",body:JSON.stringify({agentId})});toast("Lead assigned");const d=await api(`/api/leads/${id}`);openModal(d.data.name||"Lead",leadModalHtml(d.data))}catch(e){toast(e.message,true)}}
async function moveLeadFromModal(id){const stage=document.getElementById("modalStage").value;try{await api(`/api/leads/${id}/stage`,{method:"POST",body:JSON.stringify({stage})});closeModal();toast("Stage updated");loadLeadManager()}catch(e){toast(e.message,true)}}
async function deleteLead(id){if(!confirm("Delete this lead from the local Lead Manager?"))return;try{await api(`/api/leads/${id}`,{method:"DELETE"});closeModal();toast("Lead deleted");loadLeadManager()}catch(e){toast(e.message,true)}}

async function openLeadSender(id){try{const d=await api(`/api/leads/${id}`);const l=d.data;openMessageModal(l)}catch(e){toast(e.message,true)}}
function approvedTemplates(){return templates.filter(t=>String(t.status).toUpperCase()==="APPROVED")}
function templateOptionHtml(selected=""){return`<option value="">Select approved template</option>`+approvedTemplates().map(t=>`<option value="${esc(t.name+"||"+t.language)}" ${selected===t.name+"||"+t.language?"selected":""}>${esc(t.name)} · ${esc(t.language)}</option>`).join("")}
function getSelectedTemplateFromValue(v){const [name,language]=String(v||"").split("||");return templates.find(t=>t.name===name&&t.language===language)}
function templateVariables(t){const out=[];(t?.components||[]).forEach(c=>{const type=String(c.type||"").toUpperCase();if(type==="BODY"||type==="HEADER"){(String(c.text||"").match(/\{\{\d+\}\}/g)||[]).forEach((x)=>out.push({placeholder:x,component:type}))}});return out}
function templateButtons(t){const c=(t?.components||[]).find(x=>String(x.type).toUpperCase()==="BUTTONS");return c?.buttons||[]}
function hasImage(t){return(t?.components||[]).some(c=>String(c.type).toUpperCase()==="HEADER"&&String(c.format).toUpperCase()==="IMAGE")}
function templatePreview(t){if(!t)return"";const body=(t.components||[]).find(c=>String(c.type).toUpperCase()==="BODY")?.text||"No body text";const head=(t.components||[]).find(c=>String(c.type).toUpperCase()==="HEADER");const buttons=templateButtons(t);return`<div class="preview">${head?.format==="IMAGE"?"<div class='hint'>🖼️ Fixed image header will be attached automatically.</div>":""}<div style="white-space:pre-wrap">${esc(body)}</div>${buttons.map(b=>`<div class="button-preview">${esc(b.text||b.type)}</div>`).join("")}</div>`}
function templateDynamicHtml(t,prefix,existingVars=[]){if(!t)return"";const vars=templateVariables(t),buttons=templateButtons(t);let html=`${templatePreview(t)}`;if(hasImage(t)){const key=t.name+"::"+t.language;const url=templateConfigs[key]?.mediaUrl||"";html+=`<div class="field" style="margin-top:10px"><label>Fixed template image</label><input id="${prefix}Media" value="${esc(url)}" placeholder="https://public-image-url.com/image.jpg"><div class="hint">This is required for image-header templates. It is saved per template.</div></div>`}if(vars.length){html+=`<div style="margin-top:12px"><label>Template variables</label><div class="form-grid">${vars.map((v,i)=>`<div class="field"><label>${esc(v.component)} · ${esc(v.placeholder)}</label><input class="${prefix}-var" data-index="${i}" value="${esc(existingVars[i]||"")}" placeholder="Enter value"></div>`).join("")}</div></div>`}if(buttons.length){html+=`<div style="margin-top:12px"><label>Approved buttons</label>${buttons.map((b,i)=>`<div class="field"><label>Button ${i+1} · ${esc(b.type)}</label><input value="${esc(b.text||"")}" readonly><div class="hint">Button text comes from the approved Meta template and cannot be edited here.${String(b.type).toUpperCase()==="QUICK_REPLY"?" You may optionally provide a payload below.":""}</div>${String(b.type).toUpperCase()==="QUICK_REPLY"?`<input class="${prefix}-payload" data-index="${i}" placeholder="Reply payload (optional)" style="margin-top:6px">`:""}</div>`).join("")}</div>`}return html}
async function ensureTemplateConfig(t,prefix){if(!hasImage(t))return"";const e=document.getElementById(prefix+"Media");const url=e?.value.trim();if(url){await api("/api/templates/config",{method:"POST",body:JSON.stringify({name:t.name,language:t.language,mediaUrl:url})});templateConfigs[t.name+"::"+t.language]={mediaUrl:url}}return url}
function collectSenderData(t,prefix){return{variables:[...document.querySelectorAll(`.${prefix}-var`)].sort((a,b)=>Number(a.dataset.index)-Number(b.dataset.index)).map(x=>x.value.trim()),buttonPayloads:Object.fromEntries([...document.querySelectorAll(`.${prefix}-payload`)].map(x=>[x.dataset.index,x.value.trim()]))}}

function openMessageModal(l,mode="template"){openModal(`WhatsApp · ${l.name}`,`<div class="two-col"><div><div class="card"><div class="lead-top"><div class="avatar">${esc(initials(l.name))}</div><div><div class="lead-name">${esc(l.name)}</div><div class="lead-phone">${esc(l.phone)} · ${esc(l.language||"")}</div>${stagePill(l.stage||"New")}</div></div><div class="hint" style="margin-top:10px">Contacted: ${fmt(l.contactedAt)}</div></div><div class="card" style="margin-top:14px"><div class="field"><label>Message type</label><select id="msgType" onchange="renderLeadMessageFields()"><option value="template">Approved Meta Template</option><option value="text">Custom Free Message</option></select></div><div class="field"><label>Template</label><select id="msgTemplate" onchange="renderLeadMessageFields()">${templateOptionHtml()}</select></div><div id="leadMessageFields"></div><button class="btn btn-primary" id="leadSendBtn" onclick="sendLeadFromModal('${l.id}')">Send WhatsApp</button></div></div><div class="card"><h3>Why this message?</h3><p class="hint">Outbound initiation uses an approved Meta template. Media, variables and buttons are rendered according to the selected approved template.</p><div id="leadMessagePreview" style="margin-top:12px"></div></div></div>`);renderLeadMessageFields()}
function renderLeadMessageFields(){const type=document.getElementById("msgType")?.value||"template",c=document.getElementById("leadMessageFields");if(!c)return;if(type==="text"){document.getElementById("msgTemplate").disabled=true;c.innerHTML=`<div class="field"><label>Custom message</label><textarea id="leadCustomText" placeholder="Write a message…"></textarea></div>`;document.getElementById("leadMessagePreview").innerHTML="";return}document.getElementById("msgTemplate").disabled=false;const t=getSelectedTemplateFromValue(document.getElementById("msgTemplate").value);c.innerHTML=templateDynamicHtml(t,"lead");document.getElementById("leadMessagePreview").innerHTML=t?templatePreview(t):""}
async function sendLeadFromModal(id){const l=(await api(`/api/leads/${id}`)).data;const type=document.getElementById("msgType").value;try{document.getElementById("leadSendBtn").disabled=true;if(type==="text"){await api(`/api/leads/${id}/send`,{method:"POST",body:JSON.stringify({type:"text",text:document.getElementById("leadCustomText").value,action:"manual"})})}else{const t=getSelectedTemplateFromValue(document.getElementById("msgTemplate").value);if(!t)return toast("Select a template");const x=collectSenderData(t,"lead");const media=await ensureTemplateConfig(t,"lead");await api(`/api/leads/${id}/send`,{method:"POST",body:JSON.stringify({type:"template",templateName:t.name,language:t.language,variables:x.variables,mediaUrl:media,buttonPayloads:x.buttonPayloads,action:actionForLead(l)})})}closeModal();toast("Message accepted by Meta");await loadLeadManager()}catch(e){toast(e.message,true)}finally{const b=document.getElementById("leadSendBtn");if(b)b.disabled=false}}
function actionForLead(l){if(!l.contactedAt)return"initial";if(!l.followup1SentAt)return"followup1";if(!l.followup2SentAt)return"followup2";return"completed"}

function openStageBroadcast(){const ids=[...selectedLeadIds];if(!ids.length)return toast("Select at least one lead");openModal("Send follow-up to selected leads",`<div class="field"><label>Approved template</label><select id="bulkStageTemplate" onchange="renderStageBroadcastFields()">${templateOptionHtml()}</select></div><div id="stageBroadcastFields"></div><div class="actions"><button class="btn btn-light" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="sendStageBroadcast(${JSON.stringify(ids).replaceAll('"','&quot;')})">Send to ${ids.length} leads</button></div>`)}
function renderStageBroadcastFields(){const t=getSelectedTemplateFromValue(document.getElementById("bulkStageTemplate")?.value);document.getElementById("stageBroadcastFields").innerHTML=t?templateDynamicHtml(t,"bulkstage"):""}
async function sendStageBroadcast(ids){const t=getSelectedTemplateFromValue(document.getElementById("bulkStageTemplate").value);if(!t)return toast("Select a template");try{const x=collectSenderData(t,"bulkstage");const media=await ensureTemplateConfig(t,"bulkstage");const action=ids.map(id=>leads.find(l=>l.id===id)).some(l=>!l?.contactedAt)?"initial":(ids.map(id=>leads.find(l=>l.id===id)).every(l=>l?.followup1SentAt&&!l?.followup2SentAt)?"followup2":"followup1");const r=await api("/api/campaigns",{method:"POST",body:JSON.stringify({name:`Lead Manager · ${selectedStage}`,leadIds:ids,templateName:t.name,language:t.language,action,delayMs:900,variablesByLead:Object.fromEntries(ids.map(id=>[id,x.variables])),mediaUrl:media})});closeModal();selectedLeadIds.clear();toast(`Broadcast started for ${r.total} leads`);showSection("broadcast")}catch(e){toast(e.message,true)}}

async function syncTemplates(){try{toast("Syncing templates…");const d=await api("/api/templates/sync",{method:"POST"});templates=d.data||[];await loadTemplateConfigs();renderTemplates();populateTemplateSelectors();toast(`${templates.length} templates synced`)}catch(e){toast(e.message,true)}}
async function loadTemplates(){try{const d=await api("/api/templates");templates=d.data||[];await loadTemplateConfigs();renderTemplates();populateTemplateSelectors();renderSingleSender();if(document.getElementById("broadcastTemplate")){document.getElementById("broadcastTemplate").innerHTML=templateOptionHtml();renderBroadcastFields()}}catch(e){toast(e.message,true)}}
async function loadTemplateConfigs(){try{templateConfigs=(await api("/api/templates/config")).data||{}}catch{}}
function populateTemplateSelectors(){const opts=templateOptionHtml();["singleTemplate"].forEach(id=>{const e=document.getElementById(id);if(e)e.innerHTML=opts})}
function renderTemplates(){const g=document.getElementById("templateGrid");if(!templates.length){g.innerHTML=`<div class="card empty">No templates found. Sync from Meta.</div>`;return}g.innerHTML=templates.map(t=>{const approved=String(t.status).toUpperCase()==="APPROVED",body=(t.components||[]).find(c=>String(c.type).toUpperCase()==="BODY")?.text||"No body";const buttons=templateButtons(t);const img=hasImage(t);const key=t.name+"::"+t.language;return`<div class="template-card"><div class="page-head" style="margin-bottom:8px"><div><b>${esc(t.name)}</b><div class="hint">${esc(t.language)} · ${esc(t.category||"")}</div></div><span class="badge ${approved?"badge-green":"badge-yellow"}">${esc(t.status||"")}</span></div><div class="template-body">${esc(body)}</div><div class="component-line">${img?"🖼️ Image header · fixed media configured: "+(templateConfigs[key]?.mediaUrl?"Yes":"No"):"No media header"}</div>${buttons.map(b=>`<div class="component-line">↳ ${esc(b.type)} · ${esc(b.text||"")}</div>`).join("")}${img?`<div class="template-media"><input id="media_${esc(t.id||t.name)}" value="${esc(templateConfigs[key]?.mediaUrl||"")}" placeholder="Public HTTPS image URL"><button class="btn btn-light btn-sm" style="margin-top:7px" onclick="saveTemplateMedia('${esc(t.name)}','${esc(t.language)}','media_${esc(t.id||t.name)}')">Save fixed image</button></div>`:""}</div>`}).join("")}
async function saveTemplateMedia(name,language,inputId){try{const url=document.getElementById(inputId).value.trim();await api("/api/templates/config",{method:"POST",body:JSON.stringify({name,language,mediaUrl:url})});templateConfigs[name+"::"+language]={mediaUrl:url};toast("Template media saved")}catch(e){toast(e.message,true)}}

function renderSingleSender(){const type=document.getElementById("singleType").value,t=getSelectedTemplateFromValue(document.getElementById("singleTemplate").value),c=document.getElementById("singleSenderDynamic");if(type==="text"){document.getElementById("singleTemplate").disabled=true;c.innerHTML=`<div class="field"><label>Message</label><textarea id="singleText" placeholder="Write your message…"></textarea></div>`}else{document.getElementById("singleTemplate").disabled=false;c.innerHTML=t?templateDynamicHtml(t,"single"):"<div class='hint'>Select an approved template.</div>"}}
async function sendSingle(){const country=document.getElementById("singleCountry").value,phone=document.getElementById("singlePhone").value.replace(/\D/g,"");if(!country||!phone)return toast("Select country and enter phone");try{const type=document.getElementById("singleType").value;if(type==="text"){await api("/api/messages/send",{method:"POST",body:JSON.stringify({to:country+phone,type:"text",text:document.getElementById("singleText").value})})}else{const t=getSelectedTemplateFromValue(document.getElementById("singleTemplate").value);if(!t)return toast("Select a template");const x=collectSenderData(t,"single"),media=await ensureTemplateConfig(t,"single");await api("/api/messages/send",{method:"POST",body:JSON.stringify({to:country+phone,type:"template",template:{name:t.name,language:t.language,variables:x.variables,mediaUrl:media,buttonPayloads:x.buttonPayloads}})})}toast("Message accepted by Meta")}catch(e){toast(e.message,true)}}

async function loadCountries(){try{countries=(await api("/api/countries")).data||[];document.getElementById("singleCountry").innerHTML=`<option value="">Country</option>`+countries.map(c=>`<option value="${esc(c.callingCode)}">${esc(c.name)} +${esc(c.callingCode)}</option>`).join("")}catch(e){}}
async function loadLabels(){try{const d=await api("/api/contacts/labels");const labels=d.data||[];document.getElementById("labelList").innerHTML=labels.length?labels.map(x=>{const key=encodeURIComponent(x.name);return `<span class="label-chip" style="display:inline-flex;align-items:center;gap:6px"><button class="btn btn-ghost btn-sm" style="padding:3px 6px;border:0;background:transparent" onclick="setContactLabel(decodeURIComponent('${key}'))">${esc(x.name)} · ${x.count}</button><button class="btn btn-danger btn-sm" style="padding:3px 6px" title="Delete label" onclick="event.stopPropagation();deleteContactLabel(decodeURIComponent('${key}'))">×</button></span>`}).join(""):"<span class='hint'>No labels yet.</span>";document.getElementById("contactLabelFilter").innerHTML=`<option value="">All contacts</option>`+labels.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} (${x.count})</option>`).join("")}catch(e){toast(e.message,true)}}
async function deleteContactLabel(label){if(!label)return;if(!confirm(`Delete label "${label}" from all contacts?`))return;try{const r=await api(`/api/contacts/labels?name=${encodeURIComponent(label)}`,{method:"DELETE"});toast(`Label "${label}" deleted from ${r.removed||0} contact entries`);if(document.getElementById("contactLabelFilter")?.value===label)document.getElementById("contactLabelFilter").value="";loadContacts();loadLabels();initBroadcastComposer()}catch(e){toast(e.message,true)}}
function setContactLabel(label){document.getElementById("contactLabelFilter").value=label;renderContacts()}
async function loadContacts(){try{contacts=(await api("/api/contacts")).data||[];renderContacts()}catch(e){toast(e.message,true)}}
function renderContacts(){const q=(document.getElementById("contactSearch")?.value||"").toLowerCase(),label=document.getElementById("contactLabelFilter")?.value||"";const arr=contacts.filter(c=>(!q||[c.name,c.phone,c.language].some(v=>String(v||"").toLowerCase().includes(q)))&&(!label||(c.labels||[]).includes(label)));document.getElementById("contactsTable").innerHTML=arr.length?arr.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone)}</td><td>${esc(c.language||"—")}</td><td>${esc((c.labels||[]).join(", ")||"—")}</td><td>${fmt(c.createdAt)}</td></tr>`).join(""):`<tr><td colspan="5"><div class="empty">No contacts found.</div></td></tr>`}
function parseCSV(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],n=text[i+1];if(ch==='"'&&quoted&&n==='"'){cell+='"';i++;continue}if(ch==='"'){quoted=!quoted;continue}if(ch===","&&!quoted){row.push(cell);cell="";continue}if((ch==="\n"||ch==="\r")&&!quoted){if(ch==="\r"&&n==="\n")i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell="";continue}cell+=ch}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
async function importCSV(e){const file=e.target.files[0];if(!file)return;const label=document.getElementById("csvLabel").value.trim();if(!label)return toast("Enter a label before importing",true);const rows=parseCSV(await file.text());if(rows.length<2)return toast("CSV is empty",true);const headers=rows[0].map(x=>x.trim().toLowerCase()),data=rows.slice(1).map(r=>{const o={};headers.forEach((h,i)=>o[h]=r[i]||"");const cc=String(o.countrycode||o.country_code||o.dialcode||"").replace(/\D/g,""),num=String(o.number||o.phone||o.mobile||"").replace(/\D/g,"");const vars=Object.keys(o).filter(k=>/^var\d+$/i.test(k)).sort((a,b)=>Number(a.replace(/\D/g,""))-Number(b.replace(/\D/g,""))).map(k=>o[k]);return{name:o.name||o.fullname||"",countryCode:cc,phone:cc+num,wa_id:cc+num,language:o.language||"",variables:vars}}).filter(x=>x.phone);try{const r=await api("/api/contacts/import",{method:"POST",body:JSON.stringify({contacts:data,label})});document.getElementById("importStatus").textContent=`${r.total} contacts processed under "${label}".`;toast(`${r.total} contacts imported`);loadContacts();loadLabels()}catch(err){toast(err.message,true)}}

async function loadBitrixLeads(force=false){try{const q=new URLSearchParams();const l=document.getElementById("bitrixLanguageFilter")?.value,f=document.getElementById("bitrixFrom")?.value,t=document.getElementById("bitrixTo")?.value;if(l)q.set("language",l);if(f)q.set("dateFrom",f);if(t)q.set("dateTo",t);const d=await api("/api/bitrix/leads?"+q.toString());const incoming=d.data||[];const ids=incoming.map(x=>String(x.id)).join(",");const old=bitrixLeads.map(x=>String(x.id)).join(",");if(force||ids!==old){if(!force&&incoming.length&&String(incoming[0].id)!==String(newestBitrixId)){newestBitrixId=incoming[0].id;showNewLeadNotif(incoming[0])}bitrixLeads=incoming;renderBitrixLeads()}}catch(e){document.getElementById("bitrixLeadList").innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function renderBitrixLeads(){const q=(document.getElementById("bitrixSearch")?.value||"").toLowerCase();const arr=bitrixLeads.filter(l=>{const p=Array.isArray(l.phone)?(l.phone.find(x=>x.VALUE)?.VALUE||""):l.phone||"";return !q||[l.title,p,langName(l.ufCrm_1690811363903),l.id].some(v=>String(v||"").toLowerCase().includes(q))});document.getElementById("bitrixLeadList").innerHTML=arr.length?arr.map(l=>{const p=Array.isArray(l.phone)?(l.phone.find(x=>x.VALUE)?.VALUE||""):l.phone||"";return`<div class="bitrix-item" onclick="openBitrixLead('${esc(l.id)}')"><div class="bitrix-item-title"><span class="new-dot"></span> ${esc(l.title||`Lead #${l.id}`)}</div><div class="bitrix-item-sub">${esc(p||"No phone")} · ${esc(langName(l.ufCrm_1690811363903))} · ${fmtDate(l.dateCreate)}</div></div>`}).join(""):`<div class="empty">No new Bitrix leads match these filters.</div>`}
function showNewLeadNotif(lead){const p=Array.isArray(lead.phone)?(lead.phone.find(x=>x.VALUE)?.VALUE||""):lead.phone||"";document.getElementById("newLeadText").textContent=`${lead.title||"New lead"} · ${p} · ${langName(lead.ufCrm_1690811363903)}`;document.getElementById("newLeadNotif").classList.add("show");window._newLead=lead;clearTimeout(window._notif);window._notif=setTimeout(()=>document.getElementById("newLeadNotif").classList.remove("show"),5000)}
function openNewestLead(){if(window._newLead)openBitrixLead(window._newLead.id);document.getElementById("newLeadNotif").classList.remove("show")}
async function openBitrixLead(id){try{const d=await api(`/api/bitrix/lead/${id}`);const b=d.lead;const lead=(await api("/api/leads/upsert",{method:"POST",body:JSON.stringify({bitrixId:b.id,phone:b.phone,name:b.title,language:langName(b.languageValue),source:"Meta Ads"})})).data;renderBitrixSender(lead,b)}catch(e){toast(e.message,true)}}
function renderBitrixSender(lead,b){document.getElementById("bitrixSelected").innerHTML=`<div class="lead-top"><div class="avatar">${esc(initials(lead.name))}</div><div><div class="lead-name">${esc(lead.name)}</div><div class="lead-phone">${esc(lead.phone)} · ${esc(lead.language)}</div></div></div><div class="hint" style="margin:10px 0">Bitrix ID: ${esc(b.id)} · Created: ${fmt(b.dateCreate)}</div><div class="field"><label>Message type</label><select id="bitrixMsgType" onchange="renderBitrixFields('${esc(lead.id)}')"><option value="template">Approved Meta Template</option><option value="text">Custom Free Message</option></select></div><div class="field"><label>Template</label><select id="bitrixMsgTemplate" onchange="renderBitrixFields('${esc(lead.id)}')">${templateOptionHtml()}</select></div><div id="bitrixDynamic"></div><div class="actions"><button class="btn btn-primary" onclick="sendBitrixFromPanel('${esc(lead.id)}')">Send Message</button><button class="btn btn-light" onclick="openLead('${esc(lead.id)}')">Open Lead Manager</button></div>`;renderBitrixFields(lead.id)}
function renderBitrixFields(id){const type=document.getElementById("bitrixMsgType").value,c=document.getElementById("bitrixDynamic");if(type==="text"){document.getElementById("bitrixMsgTemplate").disabled=true;c.innerHTML=`<div class="field"><label>Custom message</label><textarea id="bitrixText"></textarea></div>`;return}document.getElementById("bitrixMsgTemplate").disabled=false;const t=getSelectedTemplateFromValue(document.getElementById("bitrixMsgTemplate").value);c.innerHTML=t?templateDynamicHtml(t,"bitrix"):"<div class='hint'>Select an approved template.</div>"}
async function sendBitrixFromPanel(id){const type=document.getElementById("bitrixMsgType").value;try{if(type==="text"){const lead=(await api(`/api/leads/${id}`)).data;const w=(await api(`/api/inbox/${lead.phone}/window`)).data;if(!w.open)return toast("24-hour messaging window expired. Use an approved WhatsApp template.",true);await api(`/api/leads/${id}/send`,{method:"POST",body:JSON.stringify({type:"text",text:document.getElementById("bitrixText").value,action:"initial"})})}else{const t=getSelectedTemplateFromValue(document.getElementById("bitrixMsgTemplate").value);if(!t)return toast("Select a template");const x=collectSenderData(t,"bitrix"),media=await ensureTemplateConfig(t,"bitrix");const lead=(await api(`/api/leads/${id}`)).data;await api(`/api/leads/${id}/send`,{method:"POST",body:JSON.stringify({type:"template",templateName:t.name,language:t.language,variables:x.variables,mediaUrl:media,buttonPayloads:x.buttonPayloads,action:actionForLead(lead)})})}toast("Message accepted by Meta");await loadBitrixLeads(true);await loadLeadManager()}catch(e){toast(e.message,true)}}

async function loadCampaigns(){try{const d=await api("/api/campaigns");const rows=d.data||[];document.getElementById("campaignTable").innerHTML=rows.length?rows.map(c=>`<tr><td><b>${esc(c.name)}</b><div class="hint">${fmt(c.createdAt)}</div></td><td><span class="badge ${c.status==="completed"?"badge-green":"badge-blue"}">${esc(c.status)}</span></td><td>${c.total}</td><td>${c.sent}</td><td>${c.delivered}</td><td>${c.read}</td><td>${c.failed}</td></tr>`).join(""):`<tr><td colspan="7"><div class="empty">No campaigns yet.</div></td></tr>`}catch(e){toast(e.message,true)}}

async function loadInbox(){try{conversations=(await api("/api/inbox")).data||[];renderConversations();if(selectedConversation)await openConversation(selectedConversation)}catch(e){toast(e.message,true)}}
async function pollIncomingNotifications(){try{const data=(await api("/api/inbox")).data||[];const incoming=data.filter(c=>c.lastIncomingAt);if(!incoming.length)return;const newest=incoming.sort((a,b)=>new Date(b.lastIncomingAt)-new Date(a.lastIncomingAt))[0];const key=`${newest.wa_id}|${newest.lastIncomingId||newest.lastIncomingAt}|${newest.lastMessage||""}`;if(window._lastInboundKey===undefined){window._lastInboundKey=key;return}if(key!==window._lastInboundKey){window._lastInboundKey=key;showIncomingNotif(newest);conversations=data;if(document.getElementById("section-inbox")?.classList.contains("active"))renderConversations()}}catch(e){console.warn("Incoming notification poll failed:",e.message)}}
function renderChatMedia(m){
  if(!m?.media?.id)return "";
  const url=`/api/media/${encodeURIComponent(m.media.id)}`;
  const mime=String(m.media.mime_type||"").toLowerCase();
  if(m.type==="image"||mime.startsWith("image/"))return `<img src="${url}" alt="WhatsApp image" loading="lazy">`;
  if(m.type==="video"||mime.startsWith("video/"))return `<video src="${url}" controls preload="metadata" style="max-width:260px;border-radius:10px;display:block"></video>`;
  if(m.type==="audio"||mime.startsWith("audio/"))return `<audio src="${url}" controls style="max-width:260px"></audio>`;
  return `<a href="${url}" target="_blank" rel="noopener" class="button-preview">📎 Open ${esc(m.type||"media")}</a>`;
}
function showIncomingNotif(c){const el=document.getElementById("incomingNotif");if(!el)return;document.getElementById("incomingNotifText").textContent=`${c.contact?.name||c.wa_id}: ${c.lastMessage||"New message"}`;el.classList.add("show");window._incomingPhone=c.wa_id;clearTimeout(window._incomingNotifTimer);window._incomingNotifTimer=setTimeout(()=>el.classList.remove("show"),12000)}
function openIncomingConversation(){if(window._incomingPhone){openConversation(window._incomingPhone);document.getElementById("incomingNotif")?.classList.remove("show")}}
function renderConversations(){const q=(document.getElementById("inboxSearch")?.value||"").toLowerCase(),stage=document.getElementById("inboxStageFilter")?.value||"";const arr=conversations.filter(c=>(!stage||c.lead?.stage===stage)&&(!q||[c.contact?.name,c.wa_id,c.lastMessage].some(v=>String(v||"").toLowerCase().includes(q))));document.getElementById("conversationList").innerHTML=arr.length?arr.map(c=>`<div class="conversation ${selectedConversation===c.wa_id?"active":""}" onclick="openConversation('${esc(c.wa_id)}')"><div class="conversation-name">${esc(c.contact?.name||c.wa_id)}</div><div class="conversation-number">${esc(c.wa_id)} · ${esc(c.lead?.stage||"No stage")}</div><div class="conversation-preview">${esc(c.lastMessage||"No messages")}</div><div class="conversation-meta"><span>${fmt(c.lastMessageAt)}</span>${c.unread?`<span class="badge badge-blue">${c.unread}</span>`:""}</div></div>`).join(""):`<div class="empty">No conversations found.</div>`}
function updateComposerWindowState(){const open=!!currentMessagingWindow?.open;const box=document.getElementById("chatText"),file=document.getElementById("chatMediaFile"),send=document.querySelector(".chat-composer .btn.btn-primary");if(box){box.disabled=!open;box.placeholder=open?"Write a reply…":"Template required — 24-hour window expired"}if(file)file.disabled=!open;if(send)send.disabled=!open;}
async function openConversation(phone){selectedConversation=phone;renderConversations();try{const d=await api(`/api/inbox/${phone}/messages`),w=await api(`/api/inbox/${phone}/window`),c=conversations.find(x=>x.wa_id===phone),lead=c?.lead;currentMessagingWindow=w.data||null;document.getElementById("chatHeader").innerHTML=`<div class="chat-title"><div><div class="chat-name">${esc(c?.contact?.name||phone)}</div><div class="chat-number">${esc(phone)}</div></div><div>${stagePill(lead?.stage||"No stage")} ${lead?`<button class="btn btn-light btn-sm" onclick="openLead('${esc(lead.id)}')">Lead</button>`:""} ${lead?`<select class="btn btn-light btn-sm" onchange="assignLeadQuick('${esc(lead.id)}',this.value)" style="max-width:150px"><option value="">Unassigned</option>${(teamData?.agents||[]).map(a=>`<option value="${esc(a.id)}" ${lead.assignedAgentId===a.id?'selected':''}>${esc(a.name)}</option>`).join("")}</select>`:""}</div></div>`;document.getElementById("chatMessages").innerHTML=(d.data||[]).map(m=>{const media=renderChatMedia(m);return`<div class="message ${m.direction}">${media}<div class="message-body">${esc(m.text||"")}</div><span class="message-time">${fmt(m.timestamp)}${m.direction==="outbound"?" · "+esc(m.status||"sent"):""}</span></div>`}).join("")||`<div class="empty">No messages.</div>`;const banner=document.getElementById("messagingWindowBanner"),composer=document.querySelector(".chat-composer");if(banner){banner.classList.toggle("show",!currentMessagingWindow?.open);if(composer)composer.style.opacity=currentMessagingWindow?.open?"1":".72";updateComposerWindowState()}const box=document.getElementById("chatMessages");box.scrollTop=box.scrollHeight;await api(`/api/inbox/${phone}/read`,{method:"POST"})}catch(e){toast(e.message,true)}}
function openReengagementTemplate(){if(!selectedConversation)return;const approved=(templates||[]).filter(t=>String(t.status).toUpperCase()==="APPROVED");if(!approved.length)return toast("No approved templates are synced. Sync Templates first.",true);openModal("Re-engage customer",`<div class="hint" style="margin-bottom:10px">Customer: ${esc(selectedConversation)} · The 24-hour window is closed, so WhatsApp requires an approved template.</div><div class="field"><label>Approved template</label><select id="reengagementTemplate" onchange="renderReengagementTemplateFields()">${approved.map(t=>`<option value="${esc(t.name+"::"+t.language)}">${esc(t.name)} · ${esc(t.language)}</option>`).join("")}</select></div><div id="reengagementTemplateFields"></div><div class="actions"><button class="btn btn-primary" onclick="sendReengagementTemplate()">Send template</button><button class="btn btn-light" onclick="closeModal()">Cancel</button></div>`);renderReengagementTemplateFields()}
function renderReengagementTemplateFields(){const t=getSelectedTemplateFromValue(document.getElementById("reengagementTemplate")?.value);const c=document.getElementById("reengagementTemplateFields");if(!c)return;c.innerHTML=t?templateDynamicHtml(t,"reengagement"):"<div class='hint'>Select an approved template.</div>"}
async function sendReengagementTemplate(){try{const t=getSelectedTemplateFromValue(document.getElementById("reengagementTemplate")?.value);if(!t)return toast("Select a template",true);const x=collectSenderData(t,"reengagement"),media=await ensureTemplateConfig(t,"reengagement");await api(`/api/inbox/${selectedConversation}/send`,{method:"POST",body:JSON.stringify({type:"template",template:{name:t.name,language:t.language,variables:x.variables,mediaUrl:media,buttonPayloads:x.buttonPayloads,action:"manual"}})});closeModal();toast("Re-engagement template accepted by Meta");await loadInbox()}catch(e){toast(e.message,true)}}

async function assignLeadQuick(id,agentId){try{await api(`/api/leads/${id}/assign`,{method:"POST",body:JSON.stringify({agentId})});toast(agentId?"Conversation assigned":"Assignment removed");await loadInbox()}catch(e){toast(e.message,true)}}
let pendingChatMedia=null;
async function attachChatMedia(input){
  const file=input.files?.[0];if(!file)return;
  if(file.size>8*1024*1024){toast("Keep media under 8 MB for this composer.",true);input.value="";return}
  pendingChatMedia=file;document.getElementById("chatText").placeholder=`Attached: ${file.name} — add a caption or press Send`;
  toast(`Attached ${file.name}`);
}
async function sendChatMessage(){if(!selectedConversation)return toast("Select a conversation");const text=document.getElementById("chatText").value.trim();if(!text&&!pendingChatMedia)return;if(!currentMessagingWindow?.open)return toast("24-hour messaging window expired. Use an approved WhatsApp template to re-engage this customer.",true);try{if(pendingChatMedia){const reader=new FileReader();const data=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(pendingChatMedia)});await api(`/api/inbox/${selectedConversation}/send-media`,{method:"POST",body:JSON.stringify({mimeType:pendingChatMedia.type,filename:pendingChatMedia.name,dataUrl:data,caption:text})});pendingChatMedia=null;document.getElementById("chatMediaFile").value=""}else{await api(`/api/inbox/${selectedConversation}/send`,{method:"POST",body:JSON.stringify({type:"text",text})})}document.getElementById("chatText").value="";document.getElementById("chatText").placeholder="Write a reply…";await loadInbox()}catch(e){if(e.code===131047||e.errorCode==="131047"){currentMessagingWindow=e.window||{open:false};document.getElementById("messagingWindowBanner")?.classList.add("show");toast("24-hour window expired. Use an approved template.",true)}else toast(e.message,true)}}

function chatKeydown(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendChatMessage()}}

async function loadStatuses(){try{const q=new URLSearchParams();const p=document.getElementById("statusPhone")?.value.trim(),f=document.getElementById("statusFrom")?.value,t=document.getElementById("statusTo")?.value;if(p)q.set("phone",p);if(f)q.set("from",f);if(t)q.set("to",t);const d=await api("/api/messages/status?"+q.toString());statuses=d.data||[];document.getElementById("statusTable").innerHTML=statuses.length?statuses.map(m=>{const errs=Array.isArray(m.statusErrors)?m.statusErrors:[];const reason=errs.length?errs.map(e=>[e.code,e.title,e.message].filter(Boolean).join(" · ")).join(" | "):"";return `<tr><td>${fmt(m.timestamp)}</td><td>${esc(m.wa_id)}</td><td>${esc(m.templateName||"Free message")}</td><td style="max-width:260px;word-break:break-all">${esc(m.wamid||"—")}</td><td><span class="badge ${m.status==="read"?"badge-green":m.status==="failed"?"badge-red":"badge-blue"}">${esc(m.status||"—")}</span>${reason?`<div class="danger-text" style="font-size:9px;margin-top:4px;max-width:340px" title="${esc(reason)}">${esc(reason)}</div>`:""}</td><td>${esc(m.direction)}</td></tr>`}).join(""):`<tr><td colspan="6"><div class="empty">No messages found.</div></td></tr>`}catch(e){toast(e.message,true)}}

async function loadActivity(){try{const d=await api("/api/events");document.getElementById("activityContainer").innerHTML=(d.data||[]).map(e=>`<div style="padding:11px 0;border-bottom:1px solid rgba(20,70,100,.07)"><div style="display:flex;justify-content:space-between"><b style="font-size:10px">${esc(e.type)}</b><span class="hint">${fmt(e.timestamp)}</span></div><pre style="white-space:pre-wrap;font-size:9px;color:#718897">${esc(JSON.stringify(e.data,null,2))}</pre></div>`).join("")||`<div class="empty">No activity yet.</div>`}catch(e){toast(e.message,true)}}
async function runWhatsAppDiagnostic(){try{const el=document.getElementById("whatsappDiagnostic");el.textContent="Running…";const d=await api("/api/diagnostics/whatsapp");el.textContent=JSON.stringify(d,null,2)}catch(e){document.getElementById("whatsappDiagnostic").textContent=`Diagnostic failed: ${e.message}`}}
let followupMappingState={};
function canonicalLanguageClient(value){const x=String(value||"").toLowerCase();const map={english:["english","en","en_us","en_gb"],italiano:["italian","italiano","it","it_it"],"français":["french","français","francais","fr","fr_fr"],"español":["spanish","español","es","es_es"],română:["romanian","română","ro","ro_ro"],deutsch:["german","deutsch","de","de_de"],русский:["russian","русский","ru","ru_ru"],türkçe:["turkish","türkçe","tr","tr_tr"],polski:["polish","polski","pl","pl_pl"],português:["portuguese","português","pt","pt_pt","pt_br"],ελληνικά:["greek","ελληνικά","el","el_gr"],bosnian:["bosnian","bs","bs_ba"],bulgarian:["bulgarian","bg","bg_bg"]};for(const[k,v]of Object.entries(map))if(v.includes(x))return k;return x}
function renderFollowupMapping(approved, settings){
  const leadLangs=[...new Set((window.__leadCache||[]).map(l=>canonicalLanguageClient(l.language)).filter(Boolean))];
  const templateLangs=approved.map(t=>canonicalLanguageClient(t.language)).filter(Boolean);
  const langs=[...new Set([...leadLangs,...templateLangs])].sort();
  followupMappingState=settings.followupTemplateMap||{};
  const optionsByLang={};
  for(const lang of langs){const ts=approved.filter(t=>canonicalLanguageClient(t.language)===lang);optionsByLang[lang]=ts.map(t=>({name:t.name,label:`${t.name} · ${t.language}`}));}
  const wrap=document.getElementById("followupTemplateMap");
  if(!wrap){return;}
  wrap.innerHTML=langs.length?langs.map(lang=>{const row=followupMappingState[lang]||{};const opts=optionsByLang[lang]||[];const optionHtml=(selected)=>'<option value="">— Not mapped —</option>'+opts.map(o=>`<option value="${esc(o.name)}" ${String(selected||"")===String(o.name)?"selected":""}>${esc(o.label)}</option>`).join("");return `<div class="mapping-row"><div class="mapping-language"><b>${esc(lang)}</b><span>${opts.length} approved template${opts.length===1?"":"s"}</span></div><div class="field"><label>Follow-up 1</label><select data-fu-map="${esc(lang)}" data-action="followup1">${optionHtml(row.followup1)}</select></div><div class="field"><label>Follow-up 2</label><select data-fu-map="${esc(lang)}" data-action="followup2">${optionHtml(row.followup2)}</select></div></div>`}).join(""):'<div class="empty">No lead/template languages found yet. Sync templates and import leads first.</div>';
}
function collectFollowupMapping(){const map={};document.querySelectorAll('[data-fu-map]').forEach(el=>{const lang=el.dataset.fuMap,action=el.dataset.action;map[lang]=map[lang]||{};map[lang][action]=el.value||""});return map}
async function loadSettings(){try{const c=await api("/api/config"),s=await api("/api/settings/followups");document.getElementById("settingsPhone").textContent=c.displayPhoneNumber||c.phoneNumberId||"Not configured";document.getElementById("settingsWaba").textContent=c.wabaId||"Not configured";document.getElementById("settingsVersion").textContent=c.graphApiVersion||"—";document.getElementById("settingsStatus").textContent=c.whatsappStatus|| (c.configured?"Connected":"Incomplete");document.getElementById("webhookUrl").value=location.origin+"/webhook";document.getElementById("fu1Days").value=s.data.followup1Days;document.getElementById("fu2Days").value=s.data.followup2Days;const allLeads=await api("/api/leads?limit=500");window.__leadCache=allLeads.data||[];const t=await api("/api/templates");const approved=(t.data||[]).filter(x=>String(x.status).toUpperCase()==="APPROVED");renderFollowupMapping(approved,s.data);}catch(e){toast(e.message,true)}}
async function saveFollowupSettings(){try{const r=await api("/api/settings/followups",{method:"POST",body:JSON.stringify({followup1Days:document.getElementById("fu1Days").value,followup2Days:document.getElementById("fu2Days").value,followupTemplateMap:collectFollowupMapping()})});toast(`Sequence and language mappings saved: +${r.data.followup1Days}d / +${r.data.followup2Days}d`);await loadSettings()}catch(e){toast(e.message,true)}}
async function loadNumbers(){
  try{
    const [d,c]=await Promise.all([api("/api/numbers"),api("/api/config")]);
    const configured=Boolean(c.configured);
    const status=String(c.whatsappStatus||"").toUpperCase();
    const liveNumber=c.displayPhoneNumber||c.connectedNumber||d.active||d.data?.[0]?.number||"";
    const ok=configured && status==="CONNECTED";
    const label=ok ? `${liveNumber} · Connected` : (liveNumber ? `${liveNumber} · ${status||"Not connected"}` : "Number not configured");
    document.getElementById("connectedNumber").textContent=label;
    const dot=document.querySelector("#numberPicker .number-btn");
    if(dot){dot.classList.toggle("number-online",ok);dot.classList.toggle("number-offline",!ok);}
    document.getElementById("numberMenuList").innerHTML=`<div class="number-health">
      <div><b>${esc(c.verifiedName||"Royal Hair WhatsApp")}</b><span>${esc(liveNumber||"No number")}</span></div>
      <span class="badge ${ok?"badge-green":"badge-red"}">${esc(status||"NOT CONFIGURED")}</span>
    </div>
    <div class="number-details">Phone ID: ${esc(c.phoneNumberId||"—")}<br>WABA: ${esc(c.wabaId||"—")}<br>Platform: ${esc(c.platformType||"—")}</div>
    ${(d.data||[]).map(n=>`<button onclick="selectNumber('${esc(n.number)}')">🟢 ${esc(n.number)}<br><span class="hint">${esc(n.label)}</span></button>`).join("")||`<div class="hint" style="padding:10px">No additional numbers configured.</div>`}`;
  }catch(e){document.getElementById("connectedNumber").textContent="Number status unavailable";}
}
function selectNumber(n){document.getElementById("connectedNumber").textContent=n;document.getElementById("numberPicker").classList.remove("open");toast("Number selected in the interface. API switching will be connected during Coexistence setup.")}
function openAddNumber(){openModal("Add WhatsApp number",`<div class="field"><label>Phone number</label><input id="newNumber" placeholder="+90…"></div><div class="field"><label>Label</label><input id="newNumberLabel" placeholder="Royal Hair Production"></div><button class="btn btn-primary" onclick="addNumber()">Save number</button>`)}
async function addNumber(){try{await api("/api/numbers",{method:"POST",body:JSON.stringify({number:document.getElementById("newNumber").value,label:document.getElementById("newNumberLabel").value})});closeModal();loadNumbers();toast("Number saved to the selector")}catch(e){toast(e.message,true)}}


let contactLabels=[];
async function initBroadcastComposer(){
  try{
    const l=(await api("/api/contacts/labels")).data||[]; contactLabels=l;
    const labelOptions=l.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} (${x.count})</option>`).join("");
    const stageOptions=STAGES.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");
    document.getElementById("broadcastAudienceValue").innerHTML=labelOptions||stageOptions;
    document.getElementById("broadcastLanguage").innerHTML=`<option value="">All languages</option>`+Object.values(BITRIX_LANGUAGE_NAMES).map(x=>`<option>${esc(x)}</option>`).join("");
    document.getElementById("broadcastTemplate").innerHTML=templateOptionHtml();
    renderBroadcastAudience();
  }catch(e){}
}
function getBroadcastSelectedValues(){
  const sel=document.getElementById("broadcastAudienceValue");
  return Array.from(sel?.selectedOptions||[]).map(o=>o.value).filter(Boolean);
}
function renderBroadcastAudience(){
  const mode=document.getElementById("broadcastAudience").value, sel=document.getElementById("broadcastAudienceValue"), hint=document.getElementById("broadcastAudienceHint");
  if(mode==="label"){
    sel.multiple=true; sel.size=Math.min(7,Math.max(3,contactLabels.length||3));
    sel.innerHTML=contactLabels.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} (${x.count})</option>`).join("")||`<option value="" disabled>No labels</option>`;
    if(hint)hint.textContent="Hold Ctrl (Windows) or Cmd (Mac) to select multiple CSV labels.";
  }else{
    sel.multiple=false; sel.size=1;
    sel.innerHTML=STAGES.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");
    if(hint)hint.textContent="Select one lead stage.";
  }
  renderBroadcastFields(); updateBroadcastCount();
}
function renderBroadcastFields(){const t=getSelectedTemplateFromValue(document.getElementById("broadcastTemplate")?.value);document.getElementById("broadcastFields").innerHTML=t?templateDynamicHtml(t,"audience"):"<div class='hint'>Select an approved template.</div>"}
async function updateBroadcastCount(){
  const mode=document.getElementById("broadcastAudience").value,values=getBroadcastSelectedValues(),language=document.getElementById("broadcastLanguage").value;
  let count=0;
  if(mode==="label"){
    const wanted=new Set(values);
    count=new Set(contacts.filter(c=>(c.labels||[]).some(l=>wanted.has(l))&&(!language||String(c.language||"").toLowerCase()===language.toLowerCase())).map(c=>c.phone||c.wa_id)).size;
  }else{
    const value=values[0]||"";
    count=leads.filter(l=>l.stage===value&&(!language||String(l.language||"").toLowerCase()===language.toLowerCase())).length;
  }
  document.getElementById("broadcastAudienceCount").textContent=`${count} eligible contacts/leads`;
}
async function sendAudienceBroadcast(){
  const mode=document.getElementById("broadcastAudience").value,values=getBroadcastSelectedValues(),language=document.getElementById("broadcastLanguage").value,t=getSelectedTemplateFromValue(document.getElementById("broadcastTemplate").value);
  if(!values.length||!t)return toast("Select an audience and approved template");
  try{
    const x=collectSenderData(t,"audience"),media=await ensureTemplateConfig(t,"audience");
    if(mode==="label"){
      const wanted=new Set(values);
      const seen=new Set();
      const audience=contacts.filter(c=>{
        const phone=c.phone||c.wa_id||"";
        if(!phone||seen.has(phone)||!(c.labels||[]).some(l=>wanted.has(l)))return false;
        if(language&&String(c.language||"").toLowerCase()!==language.toLowerCase())return false;
        seen.add(phone);return true;
      });
      if(!audience.length)return toast("No eligible contacts");
      const r=await api("/api/campaigns",{method:"POST",body:JSON.stringify({name:`Labels · ${values.join(", ")}`,labels:values,contactIds:audience.map(c=>c.id),templateName:t.name,language:t.language,action:"broadcast",delayMs:900,variablesByLead:Object.fromEntries(audience.map(c=>[c.id,c.variables||x.variables])),mediaUrl:media,buttonPayloads:x.buttonPayloads})});
      toast(`Broadcast started for ${r.total} contacts`);
    }else{
      const value=values[0];
      const audience=leads.filter(l=>l.stage===value&&(!language||String(l.language||"").toLowerCase()===language.toLowerCase()));
      if(!audience.length)return toast("No eligible leads");
      const action=audience.some(l=>!l.contactedAt)?"initial":(audience.some(l=>!l.followup1SentAt)?"followup1":(audience.some(l=>!l.followup2SentAt)?"followup2":"final"));
      const r=await api("/api/campaigns",{method:"POST",body:JSON.stringify({name:`Stage · ${value}`,leadIds:audience.map(l=>l.id),templateName:t.name,language:t.language,action,autoLanguage:true,delayMs:900,variablesByLead:Object.fromEntries(audience.map(l=>[l.id,l.variables||x.variables])),mediaUrl:media,buttonPayloads:x.buttonPayloads})});
      toast(`Broadcast started for ${r.total} leads`);
    }
    showSection("broadcast");
  }catch(e){toast(e.message,true)}
}
function openContactListBroadcast(){showSection("contacts")}
document.getElementById("leadLanguage").innerHTML=`<option value="">All languages</option>`+Object.values(BITRIX_LANGUAGE_NAMES).map(x=>`<option>${esc(x)}</option>`).join("");
document.getElementById("bitrixLanguageFilter").innerHTML=`<option value="">All languages</option>`+Object.entries(BITRIX_LANGUAGE_NAMES).map(([k,v])=>`<option value="${esc(k)}">${esc(v)}</option>`).join("");
populateStageControls();


let analyticsData=null, aiSelectedLeadId=null, teamData=null;
function humanMinutes(v){if(!v)return"—";if(v<60)return`${v}m`;const h=Math.floor(v/60),m=v%60;return`${h}h ${m}m`}
async function loadAnalytics(){try{const d=await api(`/api/analytics?days=${document.getElementById("analyticsDays")?.value||30}`);analyticsData=d.data;const t=analyticsData.totals;document.getElementById("analyticsKpis").innerHTML=[[`Leads`,t.leads,"Total pipeline"],[`Response rate`,`${t.responseRate}%`,"Inbound activity / contacted"],[`Photo rate`,`${t.photoRate}%`,"Contacted leads reaching photos"],[`Avg response`,humanMinutes(t.avgResponseMinutes),"Inbound → agent reply"]].map(x=>`<div class="intel-kpi"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join("");const days=Object.entries(analyticsData.byDay||{}).slice(-31);const max=Math.max(1,...days.map(([_,x])=>Math.max(x.sent,x.received)));document.getElementById("messageChart").innerHTML=days.length?days.map(([day,x])=>`<div class="mini-bar-wrap" title="${day}: ${x.received} inbound / ${x.sent} outbound"><div style="display:flex;align-items:flex-end;gap:2px;height:100%"><i class="mini-bar" style="height:${Math.max(3,x.received/max*100)}%;flex:1;opacity:.8"></i><i class="mini-bar" style="height:${Math.max(3,x.sent/max*100)}%;flex:1;opacity:.35"></i></div><div class="mini-label">${day.slice(5)}</div></div>`).join(""):"<div class='empty'>No activity in this period.</div>";const langs=Object.entries(analyticsData.language||{}).sort((a,b)=>b[1]-a[1]);const lt=Math.max(1,...langs.map(x=>x[1]));document.getElementById("languageChart").innerHTML=langs.map(([l,n])=>`<div class="lang-row"><span>${esc(l)}</span><div class="lang-track"><i style="width:${n/lt*100}%"></i></div><b>${n}</b></div>`).join("")||`<div class='empty'>No language data yet.</div>`;const st=Object.entries(analyticsData.stage||{});const total=Math.max(1,t.leads);document.getElementById("analyticsStages").innerHTML=st.map(([x,n])=>`<div class="funnel-row"><span>${esc(x)}</span><div class="funnel-bar"><i style="width:${n/total*100}%;background:${STAGE_COLORS[x]||'#1769aa'}"></i></div><b>${n}</b></div>`).join("")}catch(e){toast(e.message,true)}}
async function loadAiAssistant(){try{const d=await api("/api/leads?limit=500");leads=d.data||[];renderAiLeadList()}catch(e){toast(e.message,true)}}
function renderAiLeadList(){const q=(document.getElementById("aiLeadSearch")?.value||"").toLowerCase();const arr=leads.filter(l=>!q||`${l.name} ${l.phone}`.toLowerCase().includes(q)).slice(0,200);document.getElementById("aiLeadList").innerHTML=arr.map(l=>`<div class="ai-lead ${aiSelectedLeadId===l.id?'active':''}" onclick="selectAiLead('${esc(l.id)}')"><b style="font-size:11px">${esc(l.name||l.phone)}</b><div class="hint">${esc(l.phone)} · ${stagePill(l.stage||'New')} ${l.detectedLanguage||l.language?`<span class='language-pill'>${esc(l.detectedLanguage||l.language)}</span>`:''}</div></div>`).join("")||`<div class="empty">No leads found.</div>`}
function selectAiLead(id){aiSelectedLeadId=id;const l=leads.find(x=>x.id===id);if(!l)return;document.getElementById("aiLeadTitle").textContent=l.name||l.phone;document.getElementById("aiLeadMeta").innerHTML=`${esc(l.phone)} · ${stagePill(l.stage||"New")} · ${esc(l.detectedLanguage||l.language||"Language not detected")}`;document.getElementById("aiResult").innerHTML=`<div class="empty">Ready to analyze ${esc(l.name||l.phone)}.</div>`;renderAiLeadList()}
async function runAiAssist(){if(!aiSelectedLeadId)return toast("Select a lead first");const el=document.getElementById("aiResult");el.innerHTML=`<div class="empty">Analyzing conversation…</div>`;try{const d=await api("/api/ai/assist",{method:"POST",body:JSON.stringify({leadId:aiSelectedLeadId,task:document.getElementById("aiTask").value,instruction:document.getElementById("aiInstruction").value})});const x=d.data;el.innerHTML=`<div class="ai-result"><div class="ai-box full"><h4>Summary · ${d.aiEnabled?'AI':'Smart fallback'}</h4><p>${esc(x.summary||'—')}</p></div><div class="ai-box"><h4>Intent</h4><p>${esc(x.intent||'—')}</p></div><div class="ai-box"><h4>Next action</h4><p>${esc(x.nextAction||'—')}</p></div><div class="ai-box"><h4>Risks / escalation</h4><p>${esc(Array.isArray(x.risks)?x.risks.join('\n'):x.risks||'None detected')}</p></div><div class="ai-box full"><h4>Suggested reply · ${esc(d.language||'—')}</h4><p>${esc(x.suggestedReply||'—')}</p><div class="actions" style="margin-top:10px"><button class="btn btn-primary btn-sm" onclick="copyAiReply()">Copy reply</button><button class="btn btn-light btn-sm" onclick="useAiReply()">Open in Inbox</button></div></div></div>`;window._aiReply=x.suggestedReply||''}catch(e){el.innerHTML=`<div class="empty danger-text">${esc(e.message)}</div>`}}
function copyAiReply(){if(window._aiReply)navigator.clipboard?.writeText(window._aiReply).then(()=>toast("Reply copied"))}
async function useAiReply(){const l=leads.find(x=>x.id===aiSelectedLeadId);if(!l)return;showSection("inbox");await new Promise(r=>setTimeout(r,150));await openConversation(l.phone);const box=document.getElementById("chatText");if(box){box.value=window._aiReply||"";box.focus();toast("Suggested reply loaded into the composer")}}
async function loadTeam(){try{teamData=await api("/api/team");const agents=teamData.agents||[];document.getElementById("agentList").innerHTML=agents.map(a=>`<div class="agent-card"><div class="agent-avatar">${esc(a.avatar||initials(a.name))}</div><div><h4>${esc(a.name)} <span class="assignment-pill">${esc(a.role)}</span></h4><p>${esc(a.email||'No email')} · ${esc(a.status||'offline')} · ${a.assignedLeads||0} assigned leads</p></div><div class="actions"><button class="btn btn-light btn-sm" onclick="useAgent('${esc(a.id)}')">Use</button><button class="btn btn-light btn-sm" onclick="editAgent('${esc(a.id)}')">Edit</button></div></div>`).join("");document.getElementById("roleList").innerHTML=Object.entries(teamData.roles||{}).map(([role,perms])=>`<div style="padding:12px 0;border-bottom:1px solid rgba(20,70,100,.07)"><b style="font-size:10px">${esc(role)}</b><div class="permission-list">${perms.map(p=>`<span class="permission">${esc(p)}</span>`).join("")}</div></div>`).join("");document.getElementById("performanceRows").innerHTML=agents.map(a=>`<div class="perf-row"><b>${esc(a.name)}</b><span>${a.assignedLeads||0}</span><span>${a.sentMessages||0}</span><span>${a.photos||0}</span><span>${a.conversionRate||0}%</span></div>`).join("")||`<div class="empty">No agents yet.</div>`}catch(e){toast(e.message,true)}}
function openAgentModal(id=null){const a=(teamData?.agents||[]).find(x=>x.id===id);openModal(id?"Edit agent":"Add agent",`<div class="form-grid"><div class="field"><label>Name</label><input id="agentName" value="${esc(a?.name||'')}"></div><div class="field"><label>Email</label><input id="agentEmail" value="${esc(a?.email||'')}"></div><div class="field"><label>Role</label><select id="agentRole">${Object.keys(teamData?.roles||{}).map(r=>`<option ${a?.role===r?'selected':''}>${esc(r)}</option>`).join("")}</select></div><div class="field"><label>Status</label><select id="agentStatus"><option ${a?.status==='online'?'selected':''}>online</option><option ${a?.status==='offline'?'selected':''}>offline</option><option ${a?.status==='away'?'selected':''}>away</option></select></div></div><div class="actions"><button class="btn btn-primary" onclick="saveAgent('${esc(id||'')}')">Save</button>${id?`<button class="btn btn-light" onclick="deleteAgent('${esc(id)}')">Remove</button>`:''}</div>`)}
function useAgent(id){localStorage.setItem("rh_agent_id",id);toast("Agent selected for this browser");loadTeam()}
function editAgent(id){openAgentModal(id)}
async function saveAgent(id){try{const body={name:document.getElementById("agentName").value,email:document.getElementById("agentEmail").value,role:document.getElementById("agentRole").value,status:document.getElementById("agentStatus").value};await api(id?`/api/team/agents/${id}`:"/api/team/agents",{method:id?"PATCH":"POST",body:JSON.stringify(body)});closeModal();await loadTeam();toast("Agent saved") }catch(e){toast(e.message,true)}}
async function deleteAgent(id){if(!confirm("Remove this agent?"))return;try{await api(`/api/team/agents/${id}`,{method:"DELETE"});closeModal();loadTeam();toast("Agent removed")}catch(e){toast(e.message,true)}}

async function initialize(){await Promise.allSettled([loadCountries(),loadTemplates(),loadContacts(),loadLabels(),loadDashboard(),loadLeadManager(),loadNumbers(),loadSettings(),loadAnalytics(),loadTeam()]);await initBroadcastComposer();loadBitrixLeads(true);await pollIncomingNotifications();if(!window._incomingPollTimer)window._incomingPollTimer=setInterval(()=>pollIncomingNotifications(),3000);if(!window._pageRefreshTimer)window._pageRefreshTimer=setInterval(()=>{if(document.getElementById("section-bitrix").classList.contains("active"))loadBitrixLeads(false);if(document.getElementById("section-lead-manager").classList.contains("active"))loadLeadManager();if(document.getElementById("section-inbox").classList.contains("active"))loadInbox();if(document.getElementById("section-dashboard").classList.contains("active"))loadDashboard()},5000)}
initialize();
